{"nbformat":4,"nbformat_minor":0,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.5"},"colab":{"name":"mushrooms.ipynb","provenance":[]}},"cells":[{"cell_type":"markdown","metadata":{"id":"9LiZC2i8ae9n"},"source":["#### Context\n","<p>Although this dataset was originally contributed to the UCI Machine Learning repository nearly 30 years ago, mushroom hunting (otherwise known as \"shrooming\") is enjoying new peaks in popularity. Learn which features spell certain death and which are most palatable in this dataset of mushroom characteristics. And how certain can your model be?</p>\n","\n","#### Content\n","<p>This dataset includes descriptions of hypothetical samples corresponding to 23 species of gilled mushrooms in the Agaricus and Lepiota Family Mushroom drawn from The Audubon Society Field Guide to North American Mushrooms (1981). Each species is identified as definitely edible, definitely poisonous, or of unknown edibility and not recommended. This latter class was combined with the poisonous one. The Guide clearly states that there is no simple rule for determining the edibility of a mushroom; no rule like \"leaflets three, let it be'' for Poisonous Oak and Ivy.</p>\n","\n","<p>Time period: Donated to UCI ML 27 April 1987</p>\n","    \n","#### Inspiration\n","<p>What types of machine learning models perform best on this dataset?\n","\n","Which features are most indicative of a poisonous mushroom?</p>"]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/","height":1000},"id":"ejgDzs5ro-YA","executionInfo":{"status":"ok","timestamp":1620120970245,"user_tz":-330,"elapsed":3266,"user":{"displayName":"Manish Kamble","photoUrl":"","userId":"03732978788362091813"}},"outputId":"9d69db46-7593-4dc8-f7ed-857d07b725de"},"source":["client.restart()"],"execution_count":53,"outputs":[{"output_type":"stream","text":["tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 10 memory: 1591 MB fds: 113>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 8 memory: 1591 MB fds: 113>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 8 memory: 1591 MB fds: 113>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 10 memory: 1591 MB fds: 113>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n"],"name":"stderr"},{"output_type":"execute_result","data":{"text/html":["<table style=\"border: 2px solid white;\">\n","<tr>\n","<td style=\"vertical-align: top; border: 0px solid white\">\n","<h3 style=\"text-align: left;\">Client</h3>\n","<ul style=\"text-align: left; list-style: none; margin: 0; padding: 0;\">\n","  <li><b>Scheduler: </b>inproc://172.28.0.2/809/1</li>\n","  <li><b>Dashboard: </b><a href='http://172.28.0.2:8787/status' target='_blank'>http://172.28.0.2:8787/status</a></li>\n","</ul>\n","</td>\n","<td style=\"vertical-align: top; border: 0px solid white\">\n","<h3 style=\"text-align: left;\">Cluster</h3>\n","<ul style=\"text-align: left; list-style:none; margin: 0; padding: 0;\">\n","  <li><b>Workers: </b>1</li>\n","  <li><b>Cores: </b>4</li>\n","  <li><b>Memory: </b>1.86 GiB</li>\n","</ul>\n","</td>\n","</tr>\n","</table>"],"text/plain":["<Client: 'inproc://172.28.0.2/809/1' processes=0 threads=0, memory=0 B>"]},"metadata":{"tags":[]},"execution_count":53},{"output_type":"stream","text":["distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 12 memory: 1591 MB fds: 113>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 12 memory: 1591 MB fds: 113>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 10 memory: 1591 MB fds: 113>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 10 memory: 1591 MB fds: 113>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"EuRsjVeOnuF5","executionInfo":{"status":"ok","timestamp":1620120972063,"user_tz":-330,"elapsed":2646,"user":{"displayName":"Manish Kamble","photoUrl":"","userId":"03732978788362091813"}},"outputId":"137b3b34-7383-4423-9b18-26853062ab90"},"source":["import numpy as np\n","import pandas as pd\n","import seaborn as sns\n","import matplotlib.pyplot as plt\n"],"execution_count":55,"outputs":[{"output_type":"stream","text":["distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"scrolled":true,"colab":{"base_uri":"https://localhost:8080/"},"id":"RT0sZNk5ae9w","executionInfo":{"status":"ok","timestamp":1620120978165,"user_tz":-330,"elapsed":6853,"user":{"displayName":"Manish Kamble","photoUrl":"","userId":"03732978788362091813"}},"outputId":"6611447f-bc2f-45c2-e384-9b8d967cb127"},"source":["!pip install dataprep"],"execution_count":56,"outputs":[{"output_type":"stream","text":["distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 22 memory: 1591 MB fds: 125>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 22 memory: 1591 MB fds: 125>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 12 memory: 1591 MB fds: 125>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 12 memory: 1591 MB fds: 125>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n"],"name":"stderr"},{"output_type":"stream","text":["Requirement already satisfied: dataprep in /usr/local/lib/python3.7/dist-packages (0.2.15)\n","Requirement already satisfied: jsonpath-ng<2.0,>=1.5 in /usr/local/lib/python3.7/dist-packages (from dataprep) (1.5.2)\n","Requirement already satisfied: numpy<2,>=1 in /usr/local/lib/python3.7/dist-packages (from dataprep) (1.19.5)\n","Requirement already satisfied: wordcloud<2.0,>=1.8 in /usr/local/lib/python3.7/dist-packages (from dataprep) (1.8.1)\n","Requirement already satisfied: bottleneck<2.0,>=1.3 in /usr/local/lib/python3.7/dist-packages (from dataprep) (1.3.2)\n","Requirement already satisfied: pandas<2,>=1 in /usr/local/lib/python3.7/dist-packages (from dataprep) (1.1.5)\n","Requirement already satisfied: nltk<4.0,>=3.5 in /usr/local/lib/python3.7/dist-packages (from dataprep) (3.6.2)\n","Requirement already satisfied: ipywidgets<8.0,>=7.5 in /usr/local/lib/python3.7/dist-packages (from dataprep) (7.6.3)\n","Requirement already satisfied: pydantic<2.0,>=1.6 in /usr/local/lib/python3.7/dist-packages (from dataprep) (1.8.1)\n","Requirement already satisfied: aiohttp<4.0,>=3.6 in /usr/local/lib/python3.7/dist-packages (from dataprep) (3.7.4.post0)\n","Requirement already satisfied: regex<2021.0.0,>=2020.10.15 in /usr/local/lib/python3.7/dist-packages (from dataprep) (2020.11.13)\n","Requirement already satisfied: bokeh<3,>=2 in /usr/local/lib/python3.7/dist-packages (from dataprep) (2.3.1)\n","Requirement already satisfied: tqdm<5.0,>=4.48 in /usr/local/lib/python3.7/dist-packages (from dataprep) (4.60.0)\n","Requirement already satisfied: dask[array,dataframe,delayed]<3.0,>=2.25 in /usr/local/lib/python3.7/dist-packages (from dataprep) (2.30.0)\n","Requirement already satisfied: scipy<2,>=1 in /usr/local/lib/python3.7/dist-packages (from dataprep) (1.4.1)\n","Requirement already satisfied: jinja2<3.0,>=2.11 in /usr/local/lib/python3.7/dist-packages (from dataprep) (2.11.3)\n","Requirement already satisfied: ply in /usr/local/lib/python3.7/dist-packages (from jsonpath-ng<2.0,>=1.5->dataprep) (3.11)\n","Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from jsonpath-ng<2.0,>=1.5->dataprep) (4.4.2)\n","Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from jsonpath-ng<2.0,>=1.5->dataprep) (1.15.0)\n","Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from wordcloud<2.0,>=1.8->dataprep) (3.4.1)\n","Requirement already satisfied: pillow in /usr/local/lib/python3.7/dist-packages (from wordcloud<2.0,>=1.8->dataprep) (7.1.2)\n","Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas<2,>=1->dataprep) (2.8.1)\n","Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas<2,>=1->dataprep) (2018.9)\n","Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from nltk<4.0,>=3.5->dataprep) (7.1.2)\n","Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from nltk<4.0,>=3.5->dataprep) (1.0.1)\n","Requirement already satisfied: jupyterlab-widgets>=1.0.0; python_version >= \"3.6\" in /usr/local/lib/python3.7/dist-packages (from ipywidgets<8.0,>=7.5->dataprep) (1.0.0)\n"],"name":"stdout"},{"output_type":"stream","text":["tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 14 memory: 1592 MB fds: 125>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 14 memory: 1592 MB fds: 125>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n"],"name":"stderr"},{"output_type":"stream","text":["Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.7/dist-packages (from ipywidgets<8.0,>=7.5->dataprep) (5.0.5)\n","Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from ipywidgets<8.0,>=7.5->dataprep) (4.10.1)\n","Requirement already satisfied: ipython>=4.0.0; python_version >= \"3.3\" in /usr/local/lib/python3.7/dist-packages (from ipywidgets<8.0,>=7.5->dataprep) (5.5.0)\n","Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets<8.0,>=7.5->dataprep) (5.1.3)\n","Requirement already satisfied: widgetsnbextension~=3.5.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets<8.0,>=7.5->dataprep) (3.5.1)\n","Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.7/dist-packages (from pydantic<2.0,>=1.6->dataprep) (3.7.4.3)\n","Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp<4.0,>=3.6->dataprep) (20.3.0)\n","Requirement already satisfied: chardet<5.0,>=2.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp<4.0,>=3.6->dataprep) (3.0.4)\n","Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.7/dist-packages (from aiohttp<4.0,>=3.6->dataprep) (5.1.0)\n","Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp<4.0,>=3.6->dataprep) (1.6.3)\n","Requirement already satisfied: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp<4.0,>=3.6->dataprep) (3.0.1)\n","Requirement already satisfied: tornado>=5.1 in /usr/local/lib/python3.7/dist-packages (from bokeh<3,>=2->dataprep) (5.1.1)\n","Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.7/dist-packages (from bokeh<3,>=2->dataprep) (3.13)\n","Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python3.7/dist-packages (from bokeh<3,>=2->dataprep) (20.9)\n","Requirement already satisfied: toolz>=0.8.2; extra == \"array\" in /usr/local/lib/python3.7/dist-packages (from dask[array,dataframe,delayed]<3.0,>=2.25->dataprep) (0.11.1)\n","Requirement already satisfied: fsspec>=0.6.0; extra == \"dataframe\" in /usr/local/lib/python3.7/dist-packages (from dask[array,dataframe,delayed]<3.0,>=2.25->dataprep) (2021.4.0)\n","Requirement already satisfied: partd>=0.3.10; extra == \"dataframe\" in /usr/local/lib/python3.7/dist-packages (from dask[array,dataframe,delayed]<3.0,>=2.25->dataprep) (1.2.0)\n","Requirement already satisfied: cloudpickle>=0.2.2; extra == \"delayed\" in /usr/local/lib/python3.7/dist-packages (from dask[array,dataframe,delayed]<3.0,>=2.25->dataprep) (1.3.0)\n","Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2<3.0,>=2.11->dataprep) (1.1.1)\n","Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->wordcloud<2.0,>=1.8->dataprep) (1.3.1)\n","Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->wordcloud<2.0,>=1.8->dataprep) (0.10.0)\n","Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->wordcloud<2.0,>=1.8->dataprep) (2.4.7)\n","Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.7/dist-packages (from traitlets>=4.3.1->ipywidgets<8.0,>=7.5->dataprep) (0.2.0)\n","Requirement already satisfied: jupyter-client in /usr/local/lib/python3.7/dist-packages (from ipykernel>=4.5.1->ipywidgets<8.0,>=7.5->dataprep) (5.3.5)\n","Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0; python_version >= \"3.3\"->ipywidgets<8.0,>=7.5->dataprep) (56.0.0)\n","Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0; python_version >= \"3.3\"->ipywidgets<8.0,>=7.5->dataprep) (1.0.18)\n","Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0; python_version >= \"3.3\"->ipywidgets<8.0,>=7.5->dataprep) (2.6.1)\n","Requirement already satisfied: pexpect; sys_platform != \"win32\" in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0; python_version >= \"3.3\"->ipywidgets<8.0,>=7.5->dataprep) (4.8.0)\n","Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0; python_version >= \"3.3\"->ipywidgets<8.0,>=7.5->dataprep) (0.7.5)\n","Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0; python_version >= \"3.3\"->ipywidgets<8.0,>=7.5->dataprep) (0.8.1)\n","Requirement already satisfied: jupyter-core in /usr/local/lib/python3.7/dist-packages (from nbformat>=4.2.0->ipywidgets<8.0,>=7.5->dataprep) (4.7.1)\n","Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python3.7/dist-packages (from nbformat>=4.2.0->ipywidgets<8.0,>=7.5->dataprep) (2.6.0)\n","Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.7/dist-packages (from widgetsnbextension~=3.5.0->ipywidgets<8.0,>=7.5->dataprep) (5.3.1)\n","Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.7/dist-packages (from yarl<2.0,>=1.0->aiohttp<4.0,>=3.6->dataprep) (2.10)\n","Requirement already satisfied: locket in /usr/local/lib/python3.7/dist-packages (from partd>=0.3.10; extra == \"dataframe\"->dask[array,dataframe,delayed]<3.0,>=2.25->dataprep) (0.2.1)\n","Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python3.7/dist-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets<8.0,>=7.5->dataprep) (21.0.2)\n","Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0; python_version >= \"3.3\"->ipywidgets<8.0,>=7.5->dataprep) (0.2.5)\n","Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect; sys_platform != \"win32\"->ipython>=4.0.0; python_version >= \"3.3\"->ipywidgets<8.0,>=7.5->dataprep) (0.7.0)\n","Requirement already satisfied: nbconvert in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8.0,>=7.5->dataprep) (5.6.1)\n"],"name":"stdout"},{"output_type":"stream","text":["distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 12 memory: 1592 MB fds: 125>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 10 memory: 1592 MB fds: 125>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n"],"name":"stderr"},{"output_type":"stream","text":["Requirement already satisfied: Send2Trash in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8.0,>=7.5->dataprep) (1.5.0)\n","Requirement already satisfied: terminado>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8.0,>=7.5->dataprep) (0.9.4)\n","Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8.0,>=7.5->dataprep) (0.8.4)\n","Requirement already satisfied: bleach in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8.0,>=7.5->dataprep) (3.3.0)\n","Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8.0,>=7.5->dataprep) (1.4.3)\n","Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8.0,>=7.5->dataprep) (0.3)\n","Requirement already satisfied: testpath in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8.0,>=7.5->dataprep) (0.4.4)\n","Requirement already satisfied: defusedxml in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8.0,>=7.5->dataprep) (0.7.1)\n","Requirement already satisfied: webencodings in /usr/local/lib/python3.7/dist-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<8.0,>=7.5->dataprep) (0.5.1)\n"],"name":"stdout"},{"output_type":"stream","text":["distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 8 memory: 1592 MB fds: 125>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 10 memory: 1592 MB fds: 125>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 10 memory: 1592 MB fds: 125>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 10 memory: 1592 MB fds: 125>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 10 memory: 1592 MB fds: 125>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 10 memory: 1592 MB fds: 125>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 10 memory: 1592 MB fds: 125>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 10 memory: 1592 MB fds: 125>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"scrolled":true,"id":"-PzphJaVae9x","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1620119191849,"user_tz":-330,"elapsed":1049,"user":{"displayName":"Manish Kamble","photoUrl":"","userId":"03732978788362091813"}},"outputId":"d4edb032-2fe5-41f1-b97b-20edf25c9e86"},"source":["from dataprep.eda import create_report"],"execution_count":null,"outputs":[{"output_type":"stream","text":["tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 12 memory: 1409 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 12 memory: 1409 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"deXAHDyRcL4f","executionInfo":{"status":"ok","timestamp":1620119224573,"user_tz":-330,"elapsed":1159,"user":{"displayName":"Manish Kamble","photoUrl":"","userId":"03732978788362091813"}},"outputId":"805d777c-3bf9-47f9-9be9-69d731dcee02"},"source":["from google.colab import drive\n","drive.mount(\"/content/drive\")"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"],"name":"stdout"},{"output_type":"stream","text":["distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"pCtHcrjdc96I","executionInfo":{"status":"ok","timestamp":1620119229340,"user_tz":-330,"elapsed":1211,"user":{"displayName":"Manish Kamble","photoUrl":"","userId":"03732978788362091813"}},"outputId":"dfec5174-0c9c-4641-e265-afa70e0ffbb6"},"source":["from google.colab import drive\n","drive.mount('/content/drive')"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"],"name":"stdout"},{"output_type":"stream","text":["distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 14 memory: 1409 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 14 memory: 1409 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"4PbCkGMOd4vT","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1620119232695,"user_tz":-330,"elapsed":1274,"user":{"displayName":"Manish Kamble","photoUrl":"","userId":"03732978788362091813"}},"outputId":"40c45d30-920e-4675-b146-5b2597fadd5d"},"source":["path = \"/content/drive/MyDrive/Colab Notebooks/kaggle/mushrooms.csv\""],"execution_count":null,"outputs":[{"output_type":"stream","text":["distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 10 memory: 1409 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 10 memory: 1409 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 10 memory: 1409 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"scrolled":true,"id":"gYHKX5SQae90","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1620119234599,"user_tz":-330,"elapsed":1217,"user":{"displayName":"Manish Kamble","photoUrl":"","userId":"03732978788362091813"}},"outputId":"36d6e8b8-6f7e-4714-d786-9a852eab9b92"},"source":["df = pd.read_csv(path)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 16 memory: 1409 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 16 memory: 1409 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"scrolled":true,"id":"2b8yQaDdae90","colab":{"base_uri":"https://localhost:8080/","height":291},"executionInfo":{"status":"ok","timestamp":1620119235983,"user_tz":-330,"elapsed":908,"user":{"displayName":"Manish Kamble","photoUrl":"","userId":"03732978788362091813"}},"outputId":"207f9dbe-455a-4a14-f527-d0a484fe9e2a"},"source":["df.head()"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/html":["<div>\n","<style scoped>\n","    .dataframe tbody tr th:only-of-type {\n","        vertical-align: middle;\n","    }\n","\n","    .dataframe tbody tr th {\n","        vertical-align: top;\n","    }\n","\n","    .dataframe thead th {\n","        text-align: right;\n","    }\n","</style>\n","<table border=\"1\" class=\"dataframe\">\n","  <thead>\n","    <tr style=\"text-align: right;\">\n","      <th></th>\n","      <th>class</th>\n","      <th>cap-shape</th>\n","      <th>cap-surface</th>\n","      <th>cap-color</th>\n","      <th>bruises</th>\n","      <th>odor</th>\n","      <th>gill-attachment</th>\n","      <th>gill-spacing</th>\n","      <th>gill-size</th>\n","      <th>gill-color</th>\n","      <th>stalk-shape</th>\n","      <th>stalk-root</th>\n","      <th>stalk-surface-above-ring</th>\n","      <th>stalk-surface-below-ring</th>\n","      <th>stalk-color-above-ring</th>\n","      <th>stalk-color-below-ring</th>\n","      <th>veil-type</th>\n","      <th>veil-color</th>\n","      <th>ring-number</th>\n","      <th>ring-type</th>\n","      <th>spore-print-color</th>\n","      <th>population</th>\n","      <th>habitat</th>\n","    </tr>\n","  </thead>\n","  <tbody>\n","    <tr>\n","      <th>0</th>\n","      <td>p</td>\n","      <td>x</td>\n","      <td>s</td>\n","      <td>n</td>\n","      <td>t</td>\n","      <td>p</td>\n","      <td>f</td>\n","      <td>c</td>\n","      <td>n</td>\n","      <td>k</td>\n","      <td>e</td>\n","      <td>e</td>\n","      <td>s</td>\n","      <td>s</td>\n","      <td>w</td>\n","      <td>w</td>\n","      <td>p</td>\n","      <td>w</td>\n","      <td>o</td>\n","      <td>p</td>\n","      <td>k</td>\n","      <td>s</td>\n","      <td>u</td>\n","    </tr>\n","    <tr>\n","      <th>1</th>\n","      <td>e</td>\n","      <td>x</td>\n","      <td>s</td>\n","      <td>y</td>\n","      <td>t</td>\n","      <td>a</td>\n","      <td>f</td>\n","      <td>c</td>\n","      <td>b</td>\n","      <td>k</td>\n","      <td>e</td>\n","      <td>c</td>\n","      <td>s</td>\n","      <td>s</td>\n","      <td>w</td>\n","      <td>w</td>\n","      <td>p</td>\n","      <td>w</td>\n","      <td>o</td>\n","      <td>p</td>\n","      <td>n</td>\n","      <td>n</td>\n","      <td>g</td>\n","    </tr>\n","    <tr>\n","      <th>2</th>\n","      <td>e</td>\n","      <td>b</td>\n","      <td>s</td>\n","      <td>w</td>\n","      <td>t</td>\n","      <td>l</td>\n","      <td>f</td>\n","      <td>c</td>\n","      <td>b</td>\n","      <td>n</td>\n","      <td>e</td>\n","      <td>c</td>\n","      <td>s</td>\n","      <td>s</td>\n","      <td>w</td>\n","      <td>w</td>\n","      <td>p</td>\n","      <td>w</td>\n","      <td>o</td>\n","      <td>p</td>\n","      <td>n</td>\n","      <td>n</td>\n","      <td>m</td>\n","    </tr>\n","    <tr>\n","      <th>3</th>\n","      <td>p</td>\n","      <td>x</td>\n","      <td>y</td>\n","      <td>w</td>\n","      <td>t</td>\n","      <td>p</td>\n","      <td>f</td>\n","      <td>c</td>\n","      <td>n</td>\n","      <td>n</td>\n","      <td>e</td>\n","      <td>e</td>\n","      <td>s</td>\n","      <td>s</td>\n","      <td>w</td>\n","      <td>w</td>\n","      <td>p</td>\n","      <td>w</td>\n","      <td>o</td>\n","      <td>p</td>\n","      <td>k</td>\n","      <td>s</td>\n","      <td>u</td>\n","    </tr>\n","    <tr>\n","      <th>4</th>\n","      <td>e</td>\n","      <td>x</td>\n","      <td>s</td>\n","      <td>g</td>\n","      <td>f</td>\n","      <td>n</td>\n","      <td>f</td>\n","      <td>w</td>\n","      <td>b</td>\n","      <td>k</td>\n","      <td>t</td>\n","      <td>e</td>\n","      <td>s</td>\n","      <td>s</td>\n","      <td>w</td>\n","      <td>w</td>\n","      <td>p</td>\n","      <td>w</td>\n","      <td>o</td>\n","      <td>e</td>\n","      <td>n</td>\n","      <td>a</td>\n","      <td>g</td>\n","    </tr>\n","  </tbody>\n","</table>\n","</div>"],"text/plain":["  class cap-shape cap-surface  ... spore-print-color population habitat\n","0     p         x           s  ...                 k          s       u\n","1     e         x           s  ...                 n          n       g\n","2     e         b           s  ...                 n          n       m\n","3     p         x           y  ...                 k          s       u\n","4     e         x           s  ...                 n          a       g\n","\n","[5 rows x 23 columns]"]},"metadata":{"tags":[]},"execution_count":46},{"output_type":"stream","text":["distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"scrolled":true,"colab":{"base_uri":"https://localhost:8080/"},"id":"kCEDSkN8ae90","executionInfo":{"status":"ok","timestamp":1620119256270,"user_tz":-330,"elapsed":18977,"user":{"displayName":"Manish Kamble","photoUrl":"","userId":"03732978788362091813"}},"outputId":"e6f392f0-7271-436a-adc3-6ce9f23ff080"},"source":["create_report(df)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 68 memory: 1409 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 77 memory: 1409 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 94 memory: 1409 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 103 memory: 1409 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 98 memory: 1409 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 102 memory: 1409 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 102 memory: 1411 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 107 memory: 1411 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.31 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 102 memory: 1412 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.32 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 88 memory: 1412 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.32 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.32 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 99 memory: 1428 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 100 memory: 1428 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 80 memory: 1428 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 85 memory: 1428 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 106 memory: 1428 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 106 memory: 1428 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 104 memory: 1429 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 105 memory: 1429 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 106 memory: 1430 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 106 memory: 1430 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 104 memory: 1430 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 101 memory: 1430 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 123 memory: 1431 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 124 memory: 1431 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 100 memory: 1432 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 101 memory: 1432 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 106 memory: 1432 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 104 memory: 1432 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 102 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 104 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 102 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 103 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.33 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 113 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 113 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 117 memory: 1433 MB fds: 104>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 103 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 99 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 104 memory: 1433 MB fds: 104>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 106 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 98 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 94 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 100 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 105 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 103 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 99 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 100 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 101 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 104 memory: 1433 MB fds: 104>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 94 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 97 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 103 memory: 1433 MB fds: 104>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 97 memory: 1433 MB fds: 104>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 107 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 102 memory: 1433 MB fds: 104>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 93 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 101 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 99 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 96 memory: 1433 MB fds: 104>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 100 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 104 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 102 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 104 memory: 1433 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.34 GiB -- Worker memory limit: 1.86 GiB\n","tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 98 memory: 1492 MB fds: 103>>\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py\", line 1229, in _run\n","    return self.callback()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/system_monitor.py\", line 96, in update\n","    gpu_extra = nvml.one_time()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 45, in one_time\n","    h = _pynvml_handles()\n","  File \"/usr/local/lib/python3.7/dist-packages/distributed/diagnostics/nvml.py\", line 20, in _pynvml_handles\n","    count = pynvml.nvmlDeviceGetCount()\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 799, in nvmlDeviceGetCount\n","    _nvmlCheckReturn(ret)\n","  File \"/usr/local/lib/python3.7/dist-packages/pynvml.py\", line 310, in _nvmlCheckReturn\n","    raise NVMLError(ret)\n","pynvml.NVMLError_Uninitialized: Uninitialized\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"scrolled":true,"id":"dnOrHyS5ae-b","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1620119277554,"user_tz":-330,"elapsed":714,"user":{"displayName":"Manish Kamble","photoUrl":"","userId":"03732978788362091813"}},"outputId":"bff5ef7e-9060-4b75-b603-7441731ee3c7"},"source":["### Independent And Dependent Features"],"execution_count":null,"outputs":[{"output_type":"stream","text":["distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 1.48 GiB -- Worker memory limit: 1.86 GiB\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"id":"GtvDjpKwomXV"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"qdA6Zn8uae-b"},"source":["<p>AutoML library which builds ,optimizes , and evaluates machine learning pipelines using domain-specific objective function</p>"]},{"cell_type":"code","metadata":{"scrolled":true,"id":"vR3_-N-nae-b"},"source":["X = df.drop(\"class\",axis=1)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"W6jkrARLae-b"},"source":["y=df[\"class\"]"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"qSivqWeeae-c"},"source":["X.head()"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"Oe7I1KFxae-a"},"source":["#### EvalML"]},{"cell_type":"code","metadata":{"scrolled":true,"id":"tMCXVcK-ae-c"},"source":["y.value_counts(normalize=True)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"IkIJAsv-ae-c"},"source":["### Train Test Split"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"A8WwMyYWe2kD"},"source":["!pip install evalml"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"00DcxbAdiTQo"},"source":["!pip install dask distributed --upgrade"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"s9cKWwbAhqxM"},"source":["from dask.distributed import Client, progress\n","client = Client(processes=False, threads_per_worker=4,\n","                n_workers=1, memory_limit='2GB')\n","client"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"KbXKraZZae-c"},"source":["import evalml"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"WRgN5gFNae-d"},"source":["X_train,X_test,y_train,y_test =evalml.preprocessing.split_data(X,y,problem_type=\"binary\")"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"CAUu5m7Wae-d"},"source":["evalml.problem_types.ProblemTypes.all_problem_types"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"sqT3vQ0pae-d"},"source":["type(X_train)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"GZSa5Tllae-d"},"source":["X_train.head()"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"scrolled":true,"id":"ZinRxV1Yae-d"},"source":["from evalml import AutoMLSearch"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"5wmqsmUtae-d"},"source":["automl = AutoMLSearch(X_train=X_train,y_train=y_train,problem_type=\"binary\",max_batches=1,optimize_threshold=True)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"apX3vUu6ae-e"},"source":["automl.search()"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"ZHB194ULae-e"},"source":["automl.rankings"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"pkr_wdUsae-e"},"source":["automl.best_pipeline"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"vhVNWCUJae-e"},"source":["best_pipeline = automl.best_pipeline"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"cBuUt8wJae-e"},"source":["automl.describe_pipeline(automl.raning.iloc[0][\"id\"])"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"If9ma09cae-e"},"source":["#### Evaluate on test data"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"Y8_YazV5ae-f"},"source":["score = best_pipeline.score(X_holdout,y_holdout,objectives=evalml.objectives.get_core_objectives(\"binary\"))"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"x6brQHFNae-f"},"source":["print(f'Accuracy Binary : {scores[\"Accuracy Binary\"]}')"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"dVF8kQvdae-f"},"source":["best_pipeline.predict(X_test)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"DjpB-R-Qae-f"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"3mFvxJgbae-f"},"source":[""],"execution_count":null,"outputs":[]}]}